// <auto-generated />
namespace CSharpEgitimCampi301.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Mig1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig1));
        
        string IMigrationMetadata.Id
        {
            get { return "202506190847331_Mig1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
